Fix build errors
    DocoptNet\Docopt.cs(174,88): error CS1503: Argument 2: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(175,123): error CS1503: Argument 4: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(174,88): error CS1503: Argument 2: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(175,123): error CS1503: Argument 4: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(174,88): error CS1503: Argument 2: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(175,123): error CS1503: Argument 4: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(182,20): error CS8619: Nullability of reference types in value of type 'TSource[]' doesn't match target type 'IEnumerable<T>'.
    DocoptNet\Docopt.cs(174,88): error CS1503: Argument 2: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'
    DocoptNet\Docopt.cs(175,123): error CS1503: Argument 4: cannot convert from 'DocoptNet.Value' to 'DocoptNet.ValueObject'