Enable F5 debugging support for source generation (🎬 2)
Requires Visual Studio 2019 version 16.10.

F5 debugging support of source generators seems to also require
.NET SDK 5.0.300 otherwise it causes errors along the lines of:

> CSC : error CS8032: An instance of analyzer
>   DocoptNet.CodeGeneration.SourceGenerator cannot be created from
>   A:\docopt\dotnet\test\src\DocoptNet.CodeGeneration\bin\Release\netstandard2.0\DocoptNet.CodeGeneration.dll :
>   Could not load file or assembly 'Microsoft.CodeAnalysis,
>   Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
>   The system cannot find the file specified.

See also:

- https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#NETProductivity
- https://twitter.com/raboof/status/1397296571801288704